# Generated by Django 2.2.2 on 2019-07-09 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(db_column='categoryID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='store.Category'),
        ),
    ]
