# Generated by Django 2.2.2 on 2019-07-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190709_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryImgPath',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
